---
- name: Deploy and Restart Prober Timer
  hosts: all
  become: true
  tasks:
    - name: Stop prober systemd timer
      systemd:
        name: tsk-nodes-prober.timer
        state: stopped
      when: inventory_hostname in groups['prober']

    - name: Upload binary file (AMD64)
      copy:
        src: ../../bin/tsk-nodes-client-linux-amd64
        dest: /path/to/remote/tsk-nodes/bin/tsk-nodes-client
        owner: your_user
        group: your_group
        mode: 0755
      when: inventory_hostname in groups['prober'] and ansible_facts['architecture'] == 'x86_64'

    - name: Upload binary file (ARM64)
      copy:
        src: ../../bin/tsk-nodes-client-linux-arm64
        dest: /path/to/remote/tsk-nodes/bin/tsk-nodes-client
        owner: your_user
        group: your_group
        mode: 0755
      when: inventory_hostname in groups['prober'] and ansible_facts['architecture'] == 'aarch64'


    - name: Start systemd timer
      systemd:
        name: tsk-nodes-prober.timer
        state: started
      when: inventory_hostname in groups['prober']
