---
- name: Deploy and Restart Services
  hosts: all
  become: true
  tasks:
    - name: Stop server systemd daemon
      systemd:
        name: tsk-nodes-server.service
        state: stopped
      when: inventory_hostname in groups['server']

    - name: Upload binary file (AMD64)
      copy:
        src: ../../bin/tsk-nodes-server-linux-amd64
        dest: /path/to/remote/server/bin/tsk-nodes-server
        Owner: your_user
        Group: your_group
        mode: 0755
      when: inventory_hostname in groups['server'] and ansible_facts['architecture'] == 'x86_64'

    - name: Upload binary file (ARM64)
      copy:
        src: ../../bin/tsk-nodes-server-linux-arm64
        dest: /path/to/remote/server/bin/tsk-nodes-server
        Owner: your_user
        Group: your_group
        mode: 0755
      when: inventory_hostname in groups['server'] and ansible_facts['architecture'] == 'aarch64'

    - name: Start systemd daemon
      systemd:
        name: tsk-nodes-server.service
        state: started
      when: inventory_hostname in groups['server']
